# Generated by Django 3.1.3 on 2020-11-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201125_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance_modifiers',
            new_name='Balance_modifier',
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
