# Generated by Django 3.1.3 on 2020-11-25 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201125_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_modifier',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.good'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift_result',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='backend.operation'),
        ),
        migrations.AlterField(
            model_name='shift_result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Balance_modifier_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.balance_modifier')),
            ],
        ),
    ]
