# Generated by Django 3.1.3 on 2020-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201125_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wms_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
