# Generated by Django 3.1.3 on 2020-12-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201202_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_result',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='backend.fileuploader'),
        ),
    ]
