# Generated by Django 3.1.3 on 2020-12-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201202_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploader',
            name='name',
        ),
    ]
