# Generated by Django 3.1.3 on 2020-12-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_shift_result_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('picking', models.IntegerField()),
                ('transportations', models.IntegerField()),
                ('loading', models.IntegerField()),
                ('result', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Balance_modifier',
            new_name='BalanceModifier',
        ),
        migrations.RenameModel(
            old_name='Balance_modifier_history',
            new_name='BalanceModifierHistory',
        ),
        migrations.DeleteModel(
            name='Shift_result',
        ),
    ]
