# Generated by Django 3.1.3 on 2020-12-04 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_balancemodifier_for_shift_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemodifierhistory',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
