# Generated by Django 3.1.3 on 2020-12-04 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201204_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemodifierhistory',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balancemodifierhistory',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='backend.user'),
            preserve_default=False,
        ),
    ]
