# Generated by Django 3.1.3 on 2021-01-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210102_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shifts',
            new_name='Shift',
        ),
    ]
