# Generated by Django 3.1.3 on 2021-01-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210102_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-current_balance']},
        ),
    ]
