# Generated by Django 3.1.3 on 2021-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210110_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemodifierhistory',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
