# Generated by Django 3.1.3 on 2021-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_balancemodifierhistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('finished', 'finished')], default='active', max_length=20),
        ),
    ]
